server:
  port: 8085
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
  # 配置需要生成接口文档的扫描包
  packages-to-scan: com.test.doc.controller
  # 配置需要生成接口文档的接口路径
  paths-to-match: /test/**,/admin/**

spring:
#  task:
#    scheduling:
#      pool:
#        size: 10
#      thread-name-prefix: exec-task
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/almighty?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 123456

scheduler:
  # 每5秒执行一次任务
  execTaskCron: 0/15 * * * * ?

  spring.task.scheduling.pool.size=10
  spring.task.scheduling.thread-name-prefix=task-test

# 没有使用pageHelper作为分页工具，下面这部分内容忽略，也可自行改造成使用pageHelper完成分页功能
# helperDialect ：指定数据库，可以不配置，pagehelper插件会自动检测数据库的类型。
# reasonable ：分页合理化参数默认false，当该参数设置为true 时，pageNum <= 0 时，默认显示第一页，pageNum 超过 pageSize 时，显示最后一页。
# params ：用于从对象中根据属性名取值，可以配置pageNum，pageSize，count 不用配置映射的默认值。
# supportMethodsArguments ：分页插件会根据查询方法的参数中，自动根据params 配置的字段中取值，找到合适的值会自动分页。　
#pagehelper:
#  helperDialect: mysql
#  params: count=countSql
#  reasonable: true
#  supportMethodsArguments: true
#  pageSizeZero: true


# 开启sql控制台打印
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql日志